#!/usr/sbin/dtrace -qs

#pragma D option defaultargs

/*
This script was automatically generated by graphviz2dtrace version 0.1
on 2016-05-01 10:22:16.599448 UTC. To run it, make it executable with

chmod +ux

and then run it with root privileges. Example:

sudo myscript.d -c program-to-be-monitored
*/

/*
q0 mapped to 1
q1 mapped to 2
q2 mapped to 0
*/

/*
pid$target::empty:return/arg1 == 1/ mapped to 0
pid$target::pop:return mapped to 2
pid$target::push:entry mapped to 1
*/

int HAS_VERDICT;
int state;
int tf[3][3];

dtrace:::BEGIN
{
	tf[0][0] = 0;
	tf[0][1] = 2;
	tf[0][2] = 0;
	tf[1][0] = 1;
	tf[1][1] = 1;
	tf[1][2] = 1;
	tf[2][0] = 1;
	tf[2][1] = 2;
	tf[2][2] = 0;
	HAS_VERDICT = 0;
	state = ($1 ? $1: 0);
}

pid$target::empty:return
/ (arg1 == 1) && (state == 2)/
{
	trace("REJECTED");
	HAS_VERDICT = 1;
	exit(0);
}

pid$target::push:entry
/state == 2 ||
state == 0/
{
	state = tf[state][1];
}

pid$target::empty:return
/ (arg1 == 1) && (state == 0)/
{
	state = tf[state][0];
}

pid$target::pop:return
/state == 2 ||
state == 0/
{
	state = tf[state][2];
}

dtrace:::END
/ !HAS_VERDICT /
{
	trace("INCONCLUSIVE");
}

